name: Build and Test GitHub Action

on:
  push:
    branches:
    - master
    - release/*
    - dev
    - feature/*
  pull_request:
    branches:
    - feature/*

jobs:
  build_and_test:
    name: Build and test the GitHub Action
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        dotnet: [ '3.1.100' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Check Payload
      shell: bash
      run: |
        echo ${{ toJSON(github) }}

    # - name: Setup .NET SDK
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: ${{ matrix.dotnet }}

    # - name: Restore NuGet packages
    #   shell: bash
    #   run: |
    #     dotnet restore

    # - name: Build console app
    #   shell: bash
    #   run: |
    #     dotnet build

    # - name: Test console app
    #   shell: bash
    #   run: |
    #     dotnet test test/**/*.csproj

    # - name: Run the private action
    #   if: on.push.branches == 'dev'
    #   uses: ./
    #   with:
    #     authToken: ${{ secrets.GITHUB_TOKEN }}
    #     owner: aliencube
    #     repository: github-pr-merge-action
    #     issueId: '5'
    #     mergeMethod: Squash
    #     commitTitle: ''
    #     commitDescription: ''
    #     deleteBranch: 'true'
